### ISSUE TITLE
確認 +Hahow React 待研究清單 裡面提到的頁面有沒有哪些是設計不符合 style guide

### ISSUE THREAD

**Issue by echo5114** [hahow/hh-design#16]
https://paper.dropbox.com/doc/Sprint-Planning-Meeting-327-4CTxqEyJ6epU7Ry62i2sO

**Comment by danielscw** [comment]
因為現在陸陸續續都有在換 react，但是時間不太固定，所以這個就改成開發的時候有遇到再去問 designer 而不是一次全部 review 完
